/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BirthdaysRouteImport } from './routes/birthdays'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as CardsIndexRouteImport } from './routes/cards.index'
import { Route as BirthdaysIndexRouteImport } from './routes/birthdays.index'
import { Route as ListsListIdRouteImport } from './routes/lists.$listId'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'
import { Route as DocumentsFolderFolderIdRouteImport } from './routes/documents.folder.$folderId'
import { Route as DocumentsFileFileIdRouteImport } from './routes/documents.file.$fileId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdaysRoute = BirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListsRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CardsRoute,
} as any)
const BirthdaysIndexRoute = BirthdaysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BirthdaysRoute,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ListsRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => CardsRoute,
} as any)
const DocumentsFolderFolderIdRoute = DocumentsFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsFileFileIdRoute = DocumentsFileFileIdRouteImport.update({
  id: '/file/$fileId',
  path: '/file/$fileId',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthdays': typeof BirthdaysRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/callback': typeof CallbackRoute
  '/cards': typeof CardsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/birthdays/': typeof BirthdaysIndexRoute
  '/cards/': typeof CardsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/documents/file/$fileId': typeof DocumentsFileFileIdRoute
  '/documents/folder/$folderId': typeof DocumentsFolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/birthdays': typeof BirthdaysIndexRoute
  '/cards': typeof CardsIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/lists': typeof ListsIndexRoute
  '/documents/file/$fileId': typeof DocumentsFileFileIdRoute
  '/documents/folder/$folderId': typeof DocumentsFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birthdays': typeof BirthdaysRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/callback': typeof CallbackRoute
  '/cards': typeof CardsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/birthdays/': typeof BirthdaysIndexRoute
  '/cards/': typeof CardsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/documents/file/$fileId': typeof DocumentsFileFileIdRoute
  '/documents/folder/$folderId': typeof DocumentsFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/birthdays'
    | '/calendar'
    | '/callback'
    | '/cards'
    | '/documents'
    | '/lists'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/cards/$cardId'
    | '/lists/$listId'
    | '/birthdays/'
    | '/cards/'
    | '/documents/'
    | '/lists/'
    | '/documents/file/$fileId'
    | '/documents/folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/callback'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/cards/$cardId'
    | '/lists/$listId'
    | '/birthdays'
    | '/cards'
    | '/documents'
    | '/lists'
    | '/documents/file/$fileId'
    | '/documents/folder/$folderId'
  id:
    | '__root__'
    | '/'
    | '/birthdays'
    | '/calendar'
    | '/callback'
    | '/cards'
    | '/documents'
    | '/lists'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/cards/$cardId'
    | '/lists/$listId'
    | '/birthdays/'
    | '/cards/'
    | '/documents/'
    | '/lists/'
    | '/documents/file/$fileId'
    | '/documents/folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthdaysRoute: typeof BirthdaysRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CallbackRoute: typeof CallbackRoute
  CardsRoute: typeof CardsRouteWithChildren
  DocumentsRoute: typeof DocumentsRouteWithChildren
  ListsRoute: typeof ListsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthdays': {
      id: '/birthdays'
      path: '/birthdays'
      fullPath: '/birthdays'
      preLoaderRoute: typeof BirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof ListsRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/cards/': {
      id: '/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof CardsRoute
    }
    '/birthdays/': {
      id: '/birthdays/'
      path: '/'
      fullPath: '/birthdays/'
      preLoaderRoute: typeof BirthdaysIndexRouteImport
      parentRoute: typeof BirthdaysRoute
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof ListsRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof CardsRoute
    }
    '/documents/folder/$folderId': {
      id: '/documents/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/documents/folder/$folderId'
      preLoaderRoute: typeof DocumentsFolderFolderIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/file/$fileId': {
      id: '/documents/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/documents/file/$fileId'
      preLoaderRoute: typeof DocumentsFileFileIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface BirthdaysRouteChildren {
  BirthdaysIndexRoute: typeof BirthdaysIndexRoute
}

const BirthdaysRouteChildren: BirthdaysRouteChildren = {
  BirthdaysIndexRoute: BirthdaysIndexRoute,
}

const BirthdaysRouteWithChildren = BirthdaysRoute._addFileChildren(
  BirthdaysRouteChildren,
)

interface CardsRouteChildren {
  CardsCardIdRoute: typeof CardsCardIdRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsCardIdRoute: CardsCardIdRoute,
  CardsIndexRoute: CardsIndexRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface DocumentsRouteChildren {
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  DocumentsFileFileIdRoute: typeof DocumentsFileFileIdRoute
  DocumentsFolderFolderIdRoute: typeof DocumentsFolderFolderIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIndexRoute: DocumentsIndexRoute,
  DocumentsFileFileIdRoute: DocumentsFileFileIdRoute,
  DocumentsFolderFolderIdRoute: DocumentsFolderFolderIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface ListsRouteChildren {
  ListsListIdRoute: typeof ListsListIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

const ListsRouteChildren: ListsRouteChildren = {
  ListsListIdRoute: ListsListIdRoute,
  ListsIndexRoute: ListsIndexRoute,
}

const ListsRouteWithChildren = ListsRoute._addFileChildren(ListsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthdaysRoute: BirthdaysRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CallbackRoute: CallbackRoute,
  CardsRoute: CardsRouteWithChildren,
  DocumentsRoute: DocumentsRouteWithChildren,
  ListsRoute: ListsRouteWithChildren,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
