/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as CardsIndexRouteImport } from './routes/cards.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as ListsListIdRouteImport } from './routes/lists.$listId'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'
import { Route as DocumentsDocIdRouteImport } from './routes/documents.$docId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListsRoute,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CardsRoute,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ListsRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => CardsRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsDocIdRoute = DocumentsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/callback': typeof CallbackRoute
  '/cards': typeof CardsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/cards/': typeof CardsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/callback': typeof CallbackRoute
  '/documents': typeof DocumentsIndexRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/cards': typeof CardsIndexRoute
  '/lists': typeof ListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/callback': typeof CallbackRoute
  '/cards': typeof CardsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/cards/': typeof CardsIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/callback'
    | '/cards'
    | '/documents'
    | '/lists'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/cards/$cardId'
    | '/lists/$listId'
    | '/documents/$docId'
    | '/cards/'
    | '/lists/'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/callback'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/cards/$cardId'
    | '/lists/$listId'
    | '/documents/$docId'
    | '/cards'
    | '/lists'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/callback'
    | '/cards'
    | '/documents'
    | '/lists'
    | '/login'
    | '/more'
    | '/onboarding'
    | '/settings'
    | '/tasks'
    | '/cards/$cardId'
    | '/lists/$listId'
    | '/documents/$docId'
    | '/cards/'
    | '/lists/'
    | '/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CallbackRoute: typeof CallbackRoute
  CardsRoute: typeof CardsRouteWithChildren
  DocumentsRoute: typeof DocumentsRouteWithChildren
  ListsRoute: typeof ListsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof ListsRoute
    }
    '/cards/': {
      id: '/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof CardsRoute
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof ListsRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof CardsRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/$docId': {
      id: '/documents/$docId'
      path: '/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof DocumentsDocIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface CardsRouteChildren {
  CardsCardIdRoute: typeof CardsCardIdRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsCardIdRoute: CardsCardIdRoute,
  CardsIndexRoute: CardsIndexRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface ListsRouteChildren {
  ListsListIdRoute: typeof ListsListIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

const ListsRouteChildren: ListsRouteChildren = {
  ListsListIdRoute: ListsListIdRoute,
  ListsIndexRoute: ListsIndexRoute,
}

const ListsRouteWithChildren = ListsRoute._addFileChildren(ListsRouteChildren)

interface DocumentsRouteChildren {
  DocumentsDocIdRoute: typeof DocumentsDocIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocIdRoute: DocumentsDocIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(DocumentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CallbackRoute: CallbackRoute,
  CardsRoute: CardsRouteWithChildren,
  DocumentsRoute: DocumentsRouteWithChildren,
  ListsRoute: ListsRouteWithChildren,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
